export {
  getHabitats,
  getHabitat,
  createHabitat,
  createHabitat as postHabitat,
  updateHabitat,
  updateHabitat as putHabitat,
  deleteHabitat,
  getSpecies,
  getSpeciesById,
  createSpecies,
  updateSpecies,
  deleteSpecies,
  getUsers,
  getUser,
  createUser,
  updateUser,
  deleteUser,
  getJournals,
  getJournal,
  deleteJournal,
} from "./birdApi";