/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HabitatsIndexRouteImport } from './routes/habitats/index'
import { Route as HabitatsHabitatIdRouteImport } from './routes/habitats/$habitatId'
import { Route as SpeciesIndexRouteImport } from './routes/species/index'
import { Route as SpeciesSpeciesIdRouteImport } from './routes/species/$speciesId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitatsIndexRoute = HabitatsIndexRouteImport.update({
  id: '/habitats/',
  path: '/habitats/',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitatsHabitatIdRoute = HabitatsHabitatIdRouteImport.update({
  id: '/habitats/$habitatId',
  path: '/habitats/$habitatId',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeciesIndexRoute = SpeciesIndexRouteImport.update({
  id: '/species/',
  path: '/species/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeciesSpeciesIdRoute = SpeciesSpeciesIdRouteImport.update({
  id: '/species/$speciesId',
  path: '/species/$speciesId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/habitats/$habitatId': typeof HabitatsHabitatIdRoute
  '/species/$speciesId': typeof SpeciesSpeciesIdRoute
  '/habitats/': typeof HabitatsIndexRoute
  '/species/': typeof SpeciesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/habitats/$habitatId': typeof HabitatsHabitatIdRoute
  '/species/$speciesId': typeof SpeciesSpeciesIdRoute
  '/habitats': typeof HabitatsIndexRoute
  '/species': typeof SpeciesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/habitats/$habitatId': typeof HabitatsHabitatIdRoute
  '/species/$speciesId': typeof SpeciesSpeciesIdRoute
  '/habitats/': typeof HabitatsIndexRoute
  '/species/': typeof SpeciesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/habitats/$habitatId'
    | '/species/$speciesId'
    | '/habitats/'
    | '/species/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/habitats/$habitatId'
    | '/species/$speciesId'
    | '/habitats'
    | '/species'
  id:
    | '__root__'
    | '/'
    | '/habitats/$habitatId'
    | '/species/$speciesId'
    | '/habitats/'
    | '/species/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HabitatsHabitatIdRoute: typeof HabitatsHabitatIdRoute
  SpeciesSpeciesIdRoute: typeof SpeciesSpeciesIdRoute
  HabitatsIndexRoute: typeof HabitatsIndexRoute
  SpeciesIndexRoute: typeof SpeciesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habitats/': {
      id: '/habitats/'
      path: '/habitats'
      fullPath: '/habitats/'
      preLoaderRoute: typeof HabitatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habitats/$habitatId': {
      id: '/habitats/$habitatId'
      path: '/habitats/$habitatId'
      fullPath: '/habitats/$habitatId'
      preLoaderRoute: typeof HabitatsHabitatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/species/': {
      id: '/species/'
      path: '/species'
      fullPath: '/species/'
      preLoaderRoute: typeof SpeciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/species/$speciesId': {
      id: '/species/$speciesId'
      path: '/species/$speciesId'
      fullPath: '/species/$speciesId'
      preLoaderRoute: typeof SpeciesSpeciesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HabitatsHabitatIdRoute: HabitatsHabitatIdRoute,
  SpeciesSpeciesIdRoute: SpeciesSpeciesIdRoute,
  HabitatsIndexRoute: HabitatsIndexRoute,
  SpeciesIndexRoute: SpeciesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
